/* UI only; geometry in data/, persistence in state.js. */
(() => { 'use strict';
 const repo=window.MolassiRepository, state=window.MolassiState, $=id=>document.getElementById(id);
 const labels={available:'Disponibile',reserved:'Riservato',sold:'Venduto',unknown:'Da verificare'};
 let floor='p1', selected=null, hovered=null, zoom=1;
 const current=()=>repo.forFloor(floor), status=u=>state.get(u.id)||'unknown';
 repo.floors.forEach(f=>{const o=document.createElement('option');o.value=f.id;o.textContent=f.label+(f.mapped?'':' · solo tavola');$('floor').append(o)});$('floor').value=floor;
 $('plan').setAttribute('viewBox',repo.viewBox.join(' '));
 function message(text){$('notice').textContent=text}
 function detail(id){const u=repo.get(id);$('details').hidden=!u;if(!u){$('unit-title').textContent='Scegli uno spazio';$('unit-subtitle').textContent='Seleziona sulla mappa o nell’elenco.';return}
 $('unit-title').textContent=u.id;$('unit-subtitle').textContent=(u.type==='ufficio'?'Ufficio':'Appartamento')+' · Piano 1';const s=status(u);$('status-badge').textContent=labels[s];$('status-badge').className='badge '+s;$('area').textContent=u.commercialArea===null?'Da verificare':u.commercialArea+' m²';$('rooms').textContent=u.rooms??'Da verificare';$('price').textContent=u.price===null?'Da verificare':u.price+' €';$('unit-note').textContent=u.notes||'Dati letti dalla tavola; locali e prezzo non assegnati per deduzione.';$('source-note').textContent='Fonte: pagina '+u.sourcePage+' · 03/08/2026'+(u.id==='C13'?' · Venduto nel PDF.':' · Stato iniziale non dichiarato.');$('status').value=s;const editable=$('edit').checked && selected===id;$('edit-controls').hidden=!editable;$('edit-hint').hidden=editable;$('edit-hint').textContent=$('edit').checked?'Seleziona l’unità con un clic per modificarla.':'Attiva la modalità modifica per aggiornare lo stato.'; }
 function choose(id){selected=id;hovered=null;renderStates();detail(id)}
 function renderStates(){const list=current(),only=$('available').checked;let counts={available:0,reserved:0,sold:0,unknown:0};list.forEach(u=>counts[status(u)]++);
 $('counters').replaceChildren();for(const [key,n] of [['total',list.length],...Object.entries(counts)]){const el=document.createElement('div');el.className='counter';const num=document.createElement('strong');num.textContent=n;el.append(num,document.createTextNode(key==='total'?'Unità':labels[key]));$('counters').append(el)}
 document.querySelectorAll('.unit').forEach(p=>{const u=repo.get(p.dataset.id),s=status(u);p.setAttribute('class','unit '+s+(selected===u.id?' selected':'')+(only&&s!=='available'?' filtered':''));p.setAttribute('aria-label',u.id+' · '+labels[s]+' · '+u.commercialArea+' m²');p.setAttribute('aria-pressed',String(selected===u.id))});
 $('unit-list').replaceChildren();const shown=list.filter(u=>!only||status(u)==='available');$('list-count').textContent=repo.floors.find(f=>f.id===floor).mapped?shown.length+' / '+list.length:'Da mappare';shown.forEach(u=>{const b=document.createElement('button');b.className='unit-button';b.dataset.id=u.id;b.setAttribute('aria-pressed',String(u.id===selected));b.append(document.createTextNode(u.id));const sub=document.createElement('span');sub.textContent=labels[status(u)]+' · '+u.commercialArea+' m²';b.append(sub);b.addEventListener('click',()=>choose(u.id));$('unit-list').append(b)});if(!shown.length){const p=document.createElement('p');p.className='note';p.textContent=list.length?'Nessuna unità con disponibilità confermata.':'Mappatura interattiva da completare.';$('unit-list').append(p)} }
 function setZoom(value){zoom=Math.max(1,Math.min(4,value));$('plan').style.width=zoom*100+'%';$('zoom-value').textContent=Math.round(zoom*100)+'%';$('zoom-out').disabled=zoom<=1;$('zoom-in').disabled=zoom>=4}
 function renderFloor(){const f=repo.floors.find(f=>f.id===floor);selected=hovered=null;$('counters').hidden=!f.mapped;$('plan-title').textContent=f.label;$('plan-hint').textContent=f.mapped?'Passa su un’unità o selezionala per i dettagli':'Tavola originale · aree interattive non ancora mappate';$('plan-image').setAttribute('href',f.image);$('units').replaceChildren();$('available').checked=false;$('available').disabled=!f.mapped;$('edit').disabled=!f.mapped;current().forEach(u=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',u.path);p.setAttribute('class','unit');p.dataset.id=u.id;p.setAttribute('role','button');p.setAttribute('tabindex','0');p.addEventListener('click',()=>choose(u.id));p.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(u.id)}});p.addEventListener('pointerenter',()=>{hovered=u.id;detail(u.id)});p.addEventListener('pointerleave',()=>{hovered=null;detail(selected)});p.addEventListener('focus',()=>detail(u.id));p.addEventListener('blur',()=>detail(selected));$('units').append(p)});setZoom(1);$('viewport').scrollTo(0,0);renderStates();detail(null);}
 $('floor').addEventListener('change',()=>{floor=$('floor').value;renderFloor()});$('edit').addEventListener('change',()=>detail(selected));$('available').addEventListener('change',()=>{if(selected&&$('available').checked&&status(repo.get(selected))!=='available'){selected=null}renderStates();detail(selected)});
 $('zoom-in').addEventListener('click',()=>setZoom(zoom+.5));$('zoom-out').addEventListener('click',()=>setZoom(zoom-.5));$('fit').addEventListener('click',()=>{setZoom(1);$('viewport').scrollTo(0,0)});
 $('save').addEventListener('click',()=>{if(!$('edit').checked||!selected)return;const id=selected,value=$('status').value;if(state.set(id,value==='unknown'?null:value)){message('Stato di '+id+' salvato: '+labels[value]+'. Disponibile anche dopo il ricaricamento.');if($('available').checked&&value!=='available')selected=null;renderStates();detail(selected)}else message(state.warning)});
 $('plan-image').addEventListener('error',()=>message('Impossibile caricare la tavola. Verifica i file nella cartella assets/plans.'));
 renderFloor();if(state.warning)message(state.warning);
})();